services:
  wildfly:
    container_name: wildfly
    hostname: localhost
    image: quay.io/wildfly/wildfly:28.0.0.Final-jdk17
    ports:
      - "8080:8080"
    volumes:
      - ./target/lab-2-1.war:/opt/jboss/wildfly/standalone/deployments/app.war