services:
  wildfly:
    container_name: mini-cringe
    hostname: localhost
    image: quay.io/wildfly/wildfly:28.0.0.Final-jdk17
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Djboss.bind.address=0.0.0.0
    volumes:
      - ./target/lab-2-1.war:/opt/jboss/wildfly/standalone/deployments/app.war
    extra_hosts:
      - "lil-star:192.168.31.233"

  oracle:
    image: oracle/database:19.3.0-ee
    restart: always
    environment:
      - ORACLE_PWD=pswrd
      - ORACLE_ALLOW_REMOTE=true
    ports:
      - "1521:1521"
      - "5500:5500"
